export interface FeaturedCollege {
  id: string;
  name: string;
  category: 'iim' | 'premier' | 'aicte' | 'roi' | 'online' | 'btech' | 'ug';
  stream: 'mba' | 'btech' | 'online' | 'ug';
  location: string;
  state: string;
  city: string;
  fees: string;
  feeNum: number; // in Lakhs
  avgPlacement: string;
  avgPlacementNum: number; // in LPA
  highestPlacement?: string;
  cutoff: string;
  ranking: string;
  exams: string[];
  tag: string;
  tagColor: string;
  slug: string;
  rating: string;
  ownership: string;
  approvals: string;
  isHighRoi?: boolean;
  hasDiscount?: boolean;
  hasDirectAdmission?: boolean;
}

export const FEATURED_DIRECTORY_COLLEGES: FeaturedCollege[] = [
  // ── Top IIMs & Govt Elite Tier ──
  {
    id: 'iim-a',
    name: 'IIM Ahmedabad (Indian Institute of Management)',
    category: 'iim',
    stream: 'mba',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    city: 'Ahmedabad',
    fees: '₹26.5 Lakhs (Total)',
    feeNum: 26.5,
    avgPlacement: '₹35.22 LPA',
    avgPlacementNum: 35.22,
    highestPlacement: '₹1.15 Cr',
    cutoff: '99.5+ CAT %ile',
    ranking: 'NIRF #1 Management',
    exams: ['CAT'],
    tag: 'Govt • Elite Tier',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-ahmedabad',
    rating: '4.9',
    ownership: 'Government Autonomous',
    approvals: 'EQUIS, AACSB, AMBA',
  },
  {
    id: 'iim-b',
    name: 'IIM Bangalore (Indian Institute of Management)',
    category: 'iim',
    stream: 'mba',
    location: 'Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees: '₹24.5 Lakhs (Total)',
    feeNum: 24.5,
    avgPlacement: '₹33.50 LPA',
    avgPlacementNum: 33.50,
    highestPlacement: '₹1.15 Cr',
    cutoff: '99.0+ CAT %ile',
    ranking: 'NIRF #2 Management',
    exams: ['CAT'],
    tag: 'Govt • Elite Tier',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-bangalore',
    rating: '4.9',
    ownership: 'Government Autonomous',
    approvals: 'EQUIS, AACSB',
  },
  {
    id: 'iim-c',
    name: 'IIM Calcutta (Indian Institute of Management)',
    category: 'iim',
    stream: 'mba',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    city: 'Kolkata',
    fees: '₹27.0 Lakhs (Total)',
    feeNum: 27.0,
    avgPlacement: '₹35.07 LPA',
    avgPlacementNum: 35.07,
    highestPlacement: '₹1.20 Cr',
    cutoff: '99.0+ CAT %ile',
    ranking: 'NIRF #3 Management',
    exams: ['CAT'],
    tag: 'Govt • Finance Hub',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-calcutta',
    rating: '4.9',
    ownership: 'Government Autonomous',
    approvals: 'Triple Crown (EQUIS, AACSB, AMBA)',
  },
  {
    id: 'iim-l',
    name: 'IIM Lucknow',
    category: 'iim',
    stream: 'mba',
    location: 'Lucknow, Uttar Pradesh',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    fees: '₹20.7 Lakhs (Total)',
    feeNum: 20.7,
    avgPlacement: '₹32.20 LPA',
    avgPlacementNum: 32.20,
    highestPlacement: '₹65.0 LPA',
    cutoff: '98.0+ CAT %ile',
    ranking: 'NIRF #6 Management',
    exams: ['CAT'],
    tag: 'Govt • Top 6 IIM',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-lucknow',
    rating: '4.8',
    ownership: 'Government Autonomous',
    approvals: 'AACSB, AMBA',
  },
  {
    id: 'iim-k',
    name: 'IIM Kozhikode',
    category: 'iim',
    stream: 'mba',
    location: 'Kozhikode, Kerala',
    state: 'Kerala',
    city: 'Kozhikode',
    fees: '₹20.5 Lakhs (Total)',
    feeNum: 20.5,
    avgPlacement: '₹31.02 LPA',
    avgPlacementNum: 31.02,
    highestPlacement: '₹67.0 LPA',
    cutoff: '98.0+ CAT %ile',
    ranking: 'NIRF #3 Management',
    exams: ['CAT'],
    tag: 'Govt • Top 5 IIM',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-kozhikode',
    rating: '4.8',
    ownership: 'Government Autonomous',
    approvals: 'EQUIS, AMBA',
  },
  {
    id: 'iim-mumbai',
    name: 'IIM Mumbai (formerly NITIE)',
    category: 'iim',
    stream: 'mba',
    location: 'Powai, Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees: '₹21.0 Lakhs (Total)',
    feeNum: 21.0,
    avgPlacement: '₹29.70 LPA',
    avgPlacementNum: 29.70,
    highestPlacement: '₹78.0 LPA',
    cutoff: '97.5+ CAT %ile',
    ranking: 'NIRF #7 Management',
    exams: ['CAT'],
    tag: 'Supply Chain Capital',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/iim-mumbai',
    rating: '4.8',
    ownership: 'Government Autonomous',
    approvals: 'AICTE, MHRD',
  },

  // ── Premier Non-IIM Business Schools ──
  {
    id: 'xlri',
    name: 'XLRI Jamshedpur (Xavier School of Management)',
    category: 'premier',
    stream: 'mba',
    location: 'Jamshedpur, Jharkhand',
    state: 'Jharkhand',
    city: 'Jamshedpur',
    fees: '₹28.6 Lakhs (Total)',
    feeNum: 28.6,
    avgPlacement: '₹32.70 LPA',
    avgPlacementNum: 32.70,
    highestPlacement: '₹78.2 LPA',
    cutoff: '95+ XAT %ile',
    ranking: 'NIRF #9 • Asia #1 HR',
    exams: ['XAT', 'GMAT'],
    tag: 'Private • Tier-1 Non-IIM',
    tagColor: 'bg-purple-100 text-purple-900 border-purple-300',
    slug: 'colleges/xlri-jamshedpur',
    rating: '4.9',
    ownership: 'Private Autonomous',
    approvals: 'AACSB, AMBA',
  },
  {
    id: 'spjimr',
    name: 'SPJIMR Mumbai (S.P. Jain Institute of Management)',
    category: 'premier',
    stream: 'mba',
    location: 'Andheri West, Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees: '₹22.5 Lakhs (Total)',
    feeNum: 22.5,
    avgPlacement: '₹33.00 LPA',
    avgPlacementNum: 33.00,
    highestPlacement: '₹77.8 LPA',
    cutoff: '92+ CAT / XAT',
    ranking: 'FT Global Top 50 • AACSB',
    exams: ['CAT', 'XAT', 'GMAT'],
    tag: 'Profile-Based Calls',
    tagColor: 'bg-purple-100 text-purple-900 border-purple-300',
    slug: 'colleges/spjimr-mumbai',
    rating: '4.9',
    ownership: 'Private Autonomous',
    approvals: 'AACSB, AICTE',
  },
  {
    id: 'mdi-gurgaon',
    name: 'MDI Gurgaon (Management Development Institute)',
    category: 'premier',
    stream: 'mba',
    location: 'Gurgaon, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Gurgaon',
    fees: '₹25.0 Lakhs (Total)',
    feeNum: 25.0,
    avgPlacement: '₹27.67 LPA',
    avgPlacementNum: 27.67,
    highestPlacement: '₹60.0 LPA',
    cutoff: '95+ CAT %ile',
    ranking: 'NIRF #13 Management',
    exams: ['CAT', 'GMAT'],
    tag: 'Corporate Hub Flagship',
    tagColor: 'bg-blue-100 text-blue-900 border-blue-300',
    slug: 'colleges/mdi-gurgaon',
    rating: '4.8',
    ownership: 'Autonomous Institute',
    approvals: 'AACSB, AMBA, AICTE',
  },
  {
    id: 'nmims-mumbai',
    name: 'NMIMS School of Business Management (SBM)',
    category: 'premier',
    stream: 'mba',
    location: 'Vile Parle, Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees: '₹23.9 Lakhs (Total)',
    feeNum: 23.9,
    avgPlacement: '₹26.63 LPA',
    avgPlacementNum: 26.63,
    highestPlacement: '₹67.8 LPA',
    cutoff: '235+ NMAT Score',
    ranking: 'NIRF #21 • AACSB',
    exams: ['NMAT'],
    tag: 'Mumbai Financial Hub',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/nmims-mumbai',
    rating: '4.8',
    ownership: 'Deemed University',
    approvals: 'AACSB, UGC, NAAC A+',
  },
  {
    id: 'sibm-pune',
    name: 'SIBM Pune (Symbiosis Institute of Business Management)',
    category: 'premier',
    stream: 'mba',
    location: 'Lavale, Pune, Maharashtra',
    state: 'Maharashtra',
    city: 'Pune',
    fees: '₹24.2 Lakhs (Total)',
    feeNum: 24.2,
    avgPlacement: '₹26.77 LPA',
    avgPlacementNum: 26.77,
    highestPlacement: '₹49.0 LPA',
    cutoff: '98.5+ SNAP %ile',
    ranking: 'NIRF #17 • Symbiosis Flagship',
    exams: ['SNAP'],
    tag: 'Symbiosis Flagship',
    tagColor: 'bg-rose-100 text-rose-900 border-rose-300',
    slug: 'colleges/sibm-pune',
    rating: '4.8',
    ownership: 'Deemed University',
    approvals: 'NAAC A++, UGC',
  },
  {
    id: 'imt-ghaziabad',
    name: 'IMT Ghaziabad (Institute of Management Technology)',
    category: 'premier',
    stream: 'mba',
    location: 'Ghaziabad, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Ghaziabad',
    fees: '₹21.5 Lakhs (Total)',
    feeNum: 21.5,
    avgPlacement: '₹17.35 LPA',
    avgPlacementNum: 17.35,
    highestPlacement: '₹65.6 LPA',
    cutoff: '90+ CAT / XAT',
    ranking: 'AACSB Accredited • Top Mktg',
    exams: ['CAT', 'XAT', 'GMAT'],
    tag: 'Delhi NCR #1 Marketing',
    tagColor: 'bg-blue-100 text-blue-900 border-blue-300',
    slug: 'colleges/imt-ghaziabad',
    rating: '4.7',
    ownership: 'Private Autonomous',
    approvals: 'AACSB, AICTE, NBA',
  },
  {
    id: 'great-lakes-chennai',
    name: 'Great Lakes Institute of Management Chennai',
    category: 'premier',
    stream: 'mba',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Chennai',
    fees: '₹19.8 Lakhs (Total)',
    feeNum: 19.8,
    avgPlacement: '₹15.10 LPA',
    avgPlacementNum: 15.10,
    highestPlacement: '₹34.0 LPA',
    cutoff: '80+ CAT / XAT / CMAT',
    ranking: 'AMBA & SAQS Accredited',
    exams: ['CAT', 'XAT', 'CMAT', 'GMAT'],
    tag: 'Analytics & Tech MBA',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/great-lakes-chennai',
    rating: '4.7',
    ownership: 'Private Autonomous',
    approvals: 'AMBA, AICTE',
  },
  {
    id: 'gim-goa',
    name: 'Goa Institute of Management (GIM)',
    category: 'premier',
    stream: 'mba',
    location: 'Sanquelim, Goa',
    state: 'Goa',
    city: 'Goa',
    fees: '₹18.5 Lakhs (Total)',
    feeNum: 18.5,
    avgPlacement: '₹15.00 LPA',
    avgPlacementNum: 15.00,
    highestPlacement: '₹60.0 LPA',
    cutoff: '85+ CAT / XAT / CMAT / GMAT',
    ranking: 'AACSB & AMBA Accredited',
    exams: ['CAT', 'XAT', 'CMAT', 'GMAT'],
    tag: 'Healthcare & Big Data',
    tagColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    slug: 'colleges/gim-goa',
    rating: '4.7',
    ownership: 'Private Autonomous',
    approvals: 'AACSB, AMBA, AICTE',
  },

  // ── Curated AICTE & Form Combo Partner B-Schools ──
  {
    id: 'ndim-delhi',
    name: 'New Delhi Institute of Management (NDIM)',
    category: 'aicte',
    stream: 'mba',
    location: 'Tughlakabad, South Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹14.0 Lakhs (Total)',
    feeNum: 14.0,
    avgPlacement: '₹9.50 LPA',
    avgPlacementNum: 9.50,
    highestPlacement: '₹24.0 LPA',
    cutoff: '65+ CAT/MAT/CMAT or Merit',
    ranking: 'AICTE Approved • AIU MBA Eq.',
    exams: ['CAT', 'MAT', 'CMAT', 'XAT', 'Direct'],
    tag: '100% Placements • AIU Eq.',
    tagColor: 'bg-blue-100 text-blue-900 border-blue-300',
    slug: 'colleges/ndim-delhi',
    rating: '4.7',
    ownership: 'Private Autonomous',
    approvals: 'AICTE, NBA, AIU',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'fostiima',
    name: 'FOSTIIMA Business School',
    category: 'aicte',
    stream: 'mba',
    location: 'Dwarka, West Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹11.5 Lakhs (Total)',
    feeNum: 11.5,
    avgPlacement: '₹11.15 LPA',
    avgPlacementNum: 11.15,
    highestPlacement: '₹30.0 LPA',
    cutoff: '65+ CAT/XAT/CMAT or Direct',
    ranking: 'Founded by IIM-A Alumni',
    exams: ['CAT', 'XAT', 'CMAT', 'MAT', 'Direct'],
    tag: 'IIM Alumni Faculty Pool',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    slug: 'colleges/fostiima-business-school',
    rating: '4.6',
    ownership: 'Private Autonomous',
    approvals: 'AICTE Approved',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'fiib-delhi',
    name: 'Fortune Institute of International Business (FIIB)',
    category: 'aicte',
    stream: 'mba',
    location: 'Vasant Vihar, South Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹12.85 Lakhs (Total)',
    feeNum: 12.85,
    avgPlacement: '₹8.50 LPA',
    avgPlacementNum: 8.50,
    highestPlacement: '₹25.92 LPA',
    cutoff: '60+ CAT/MAT/CMAT/XAT',
    ranking: 'AACSB Member • NBA Acc.',
    exams: ['CAT', 'MAT', 'CMAT', 'XAT', 'ATMA'],
    tag: 'South Delhi Corporate Hub',
    tagColor: 'bg-purple-100 text-purple-900 border-purple-300',
    slug: 'colleges/fiib-delhi',
    rating: '4.6',
    ownership: 'Private Autonomous',
    approvals: 'AICTE, NBA, AACSB Member',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'jims-rohini',
    name: 'JIMS Rohini (Jagan Institute of Management Studies)',
    category: 'aicte',
    stream: 'mba',
    location: 'Rohini, North Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹9.25 Lakhs (Total)',
    feeNum: 9.25,
    avgPlacement: '₹8.10 LPA',
    avgPlacementNum: 8.10,
    highestPlacement: '₹22.0 LPA',
    cutoff: '70+ CAT / MAT / CMAT',
    ranking: 'NIRF Top 100 • NAAC A',
    exams: ['CAT', 'MAT', 'CMAT', 'XAT'],
    tag: 'High ROI • Delhi Metro',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/jims-rohini',
    rating: '4.6',
    ownership: 'Private Autonomous',
    approvals: 'AICTE, NBA, NAAC A',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'pibm-pune',
    name: 'PIBM Pune (Pune Institute of Business Management)',
    category: 'aicte',
    stream: 'mba',
    location: 'Pirangut, Pune, Maharashtra',
    state: 'Maharashtra',
    city: 'Pune',
    fees: '₹8.95 Lakhs (Total)',
    feeNum: 8.95,
    avgPlacement: '₹7.50 LPA',
    avgPlacementNum: 7.50,
    highestPlacement: '₹17.0 LPA',
    cutoff: '60+ CAT/XAT/MAT/CMAT/CET',
    ranking: 'Sector-Specific Practical Training',
    exams: ['CAT', 'XAT', 'MAT', 'CMAT', 'MAH CET'],
    tag: 'Pune Corporate Placement',
    tagColor: 'bg-rose-100 text-rose-900 border-rose-300',
    slug: 'colleges/pibm-pune',
    rating: '4.5',
    ownership: 'Private Autonomous',
    approvals: 'AICTE, NBA',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'soil-gurgaon',
    name: 'SOIL Institute of Management',
    category: 'aicte',
    stream: 'mba',
    location: 'Manesar / Gurgaon, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Gurgaon',
    fees: '₹15.9 Lakhs (Total)',
    feeNum: 15.9,
    avgPlacement: '₹11.20 LPA',
    avgPlacementNum: 11.20,
    highestPlacement: '₹27.0 LPA',
    cutoff: 'Profile & Leadership Call',
    ranking: 'Top Leadership Business School',
    exams: ['CAT', 'XAT', 'NMAT', 'GMAT', 'SOIL Test'],
    tag: 'Leadership & Design Thinking',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/soil-institute-of-management',
    rating: '4.6',
    ownership: 'Private Autonomous',
    approvals: 'AICTE Approved',
    hasDiscount: true,
    hasDirectAdmission: true,
  },
  {
    id: 'jagsom-bangalore',
    name: 'JAGSoM Bangalore (Jagdish Sheth School of Management)',
    category: 'aicte',
    stream: 'mba',
    location: 'Electronic City, Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees: '₹15.95 Lakhs (Total)',
    feeNum: 15.95,
    avgPlacement: '₹13.30 LPA',
    avgPlacementNum: 13.30,
    highestPlacement: '₹43.0 LPA',
    cutoff: '75+ CAT/XAT/GMAT/MAT',
    ranking: 'AACSB Accredited • QS Ranked',
    exams: ['CAT', 'XAT', 'MAT', 'CMAT', 'GMAT'],
    tag: 'Silicon Valley Tech B-School',
    tagColor: 'bg-blue-100 text-blue-900 border-blue-300',
    slug: 'colleges/jagsom-bangalore',
    rating: '4.7',
    ownership: 'Private Autonomous',
    approvals: 'AACSB, AICTE, NBA',
    hasDiscount: true,
  },

  // ── Extreme ROI Business Schools (< ₹10L Fee) ──
  {
    id: 'fms-delhi',
    name: 'FMS Delhi (Faculty of Management Studies)',
    category: 'roi',
    stream: 'mba',
    location: 'North Campus, New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹2.0 Lakhs (Total 2-Yr)',
    feeNum: 2.0,
    avgPlacement: '₹34.10 LPA',
    avgPlacementNum: 34.10,
    highestPlacement: '₹1.23 Cr',
    cutoff: '99.0+ CAT %ile',
    ranking: 'ROI Multiplier: 17x',
    exams: ['CAT'],
    tag: '17x Payback • DU Govt',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/fms-delhi',
    rating: '4.9',
    ownership: 'Government University',
    approvals: 'UGC, Delhi University',
    isHighRoi: true,
  },
  {
    id: 'jbims-mumbai',
    name: 'JBIMS Mumbai (Jamnalal Bajaj Institute)',
    category: 'roi',
    stream: 'mba',
    location: 'Churchgate, Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees: '₹6.0 Lakhs (Total 2-Yr)',
    feeNum: 6.0,
    avgPlacement: '₹28.02 LPA',
    avgPlacementNum: 28.02,
    highestPlacement: '₹44.0 LPA',
    cutoff: '99.9+ MAH CET / CAT',
    ranking: 'CEO Factory of India',
    exams: ['MAH CET', 'CAT'],
    tag: 'Highest ROI Maharashtra',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/jbims-mumbai',
    rating: '4.9',
    ownership: 'Government Autonomous',
    approvals: 'UGC, University of Mumbai',
    isHighRoi: true,
  },
  {
    id: 'dbe-du',
    name: 'DBE Delhi University (Business Economics)',
    category: 'roi',
    stream: 'mba',
    location: 'South Campus, New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹48,000 (Total 2-Yr)',
    feeNum: 0.48,
    avgPlacement: '₹14.20 LPA',
    avgPlacementNum: 14.20,
    highestPlacement: '₹32.0 LPA',
    cutoff: '93+ CAT %ile',
    ranking: 'ROI Multiplier: 29x',
    exams: ['CAT'],
    tag: '29x Payback • DU Govt',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/dbe-delhi-university',
    rating: '4.7',
    ownership: 'Government University',
    approvals: 'UGC, Delhi University',
    isHighRoi: true,
  },
  {
    id: 'dse-delhi',
    name: 'DSE Delhi School of Economics (MBA HRD & IB)',
    category: 'roi',
    stream: 'mba',
    location: 'North Campus, New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹32,000 (Total 2-Yr)',
    feeNum: 0.32,
    avgPlacement: '₹14.50 LPA',
    avgPlacementNum: 14.50,
    highestPlacement: '₹32.0 LPA',
    cutoff: '94+ CAT %ile',
    ranking: 'ROI Multiplier: 45x',
    exams: ['CAT'],
    tag: '45x Payback • DU Govt',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/dse-delhi',
    rating: '4.8',
    ownership: 'Government University',
    approvals: 'UGC, Delhi University',
    isHighRoi: true,
  },
  {
    id: 'simsree-mumbai',
    name: 'SIMSREE Mumbai (Sydenham Institute)',
    category: 'roi',
    stream: 'mba',
    location: 'Churchgate, Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees: '₹1.36 Lakhs (Total 2-Yr)',
    feeNum: 1.36,
    avgPlacement: '₹15.19 LPA',
    avgPlacementNum: 15.19,
    highestPlacement: '₹24.0 LPA',
    cutoff: '99.5+ MAH CET / CAT',
    ranking: 'ROI Multiplier: 11x',
    exams: ['MAH CET', 'CAT'],
    tag: '11x Payback • Govt Mumbai',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/simsree-mumbai',
    rating: '4.8',
    ownership: 'Government Institute',
    approvals: 'AICTE, DTE Maharashtra',
    isHighRoi: true,
  },

  // ── UGC-DEB Approved Online Degrees ──
  {
    id: 'amity-online',
    name: 'Amity University Online (MBA / MCA / BBA)',
    category: 'online',
    stream: 'online',
    location: 'Noida / 100% Online Pan-India',
    state: 'Delhi NCR',
    city: 'Noida',
    fees: '₹1.99 Lakhs (2-Yr EMI)',
    feeNum: 1.99,
    avgPlacement: 'Corporate Hiring Drives',
    avgPlacementNum: 8.5,
    highestPlacement: '₹18.0 LPA',
    cutoff: 'Direct / 50% in Grad',
    ranking: 'UGC-DEB • NAAC A+ • WES Valid',
    exams: ['Direct Admission'],
    tag: 'WES Approved • Canada/USA',
    tagColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    slug: 'online-degree-certification/amity-university-online',
    rating: '4.8',
    ownership: 'Private University (Online)',
    approvals: 'UGC-DEB, AICTE, NAAC A+, WES',
    hasDirectAdmission: true,
  },
  {
    id: 'jain-online',
    name: 'Jain University Online (JAIN Deemed-to-be)',
    category: 'online',
    stream: 'online',
    location: 'Bangalore / 100% Online Pan-India',
    state: 'Karnataka',
    city: 'Bangalore',
    fees: '₹1.96 Lakhs (2-Yr EMI)',
    feeNum: 1.96,
    avgPlacement: 'Bangalore Tech Connect',
    avgPlacementNum: 9.0,
    highestPlacement: '₹21.0 LPA',
    cutoff: 'Direct / 50% in Grad',
    ranking: 'UGC-DEB • NAAC A++ (3.71)',
    exams: ['Direct Admission'],
    tag: 'NAAC A++ Entitled',
    tagColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    slug: 'online-degree-certification/jain-university-online',
    rating: '4.8',
    ownership: 'Deemed University (Online)',
    approvals: 'UGC-DEB, NAAC A++, AICTE',
    hasDirectAdmission: true,
  },
  {
    id: 'lpu-online',
    name: 'LPU Online (Lovely Professional University)',
    category: 'online',
    stream: 'online',
    location: 'Punjab / 100% Online Pan-India',
    state: 'Punjab & Chandigarh',
    city: 'Phagwara',
    fees: '₹1.61 Lakhs (2-Yr EMI)',
    feeNum: 1.61,
    avgPlacement: 'Career Support & Drives',
    avgPlacementNum: 7.8,
    highestPlacement: '₹15.0 LPA',
    cutoff: 'Direct / 50% in Grad',
    ranking: 'UGC-DEB • NAAC A++',
    exams: ['Direct Admission'],
    tag: 'Award Winning LMS App',
    tagColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    slug: 'online-degree-certification/lovely-professional-university-lpu-online',
    rating: '4.7',
    ownership: 'Private University (Online)',
    approvals: 'UGC-DEB, NAAC A++, AICTE',
    hasDirectAdmission: true,
  },
  {
    id: 'cu-online',
    name: 'Chandigarh University Online (CU Online)',
    category: 'online',
    stream: 'online',
    location: 'Chandigarh / 100% Online Pan-India',
    state: 'Punjab & Chandigarh',
    city: 'Chandigarh',
    fees: '₹1.65 Lakhs (2-Yr EMI)',
    feeNum: 1.65,
    avgPlacement: 'Fortune 500 Network',
    avgPlacementNum: 8.0,
    highestPlacement: '₹16.0 LPA',
    cutoff: 'Direct / 50% in Grad',
    ranking: 'UGC-DEB • NAAC A+ • QS Ranked',
    exams: ['Direct Admission'],
    tag: 'QS World Ranked',
    tagColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    slug: 'online-degree-certification/chandigarh-university-online',
    rating: '4.7',
    ownership: 'Private University (Online)',
    approvals: 'UGC-DEB, NAAC A+, AICTE',
    hasDirectAdmission: true,
  },

  // ── Premier B.Tech & Engineering Hubs ──
  {
    id: 'iit-delhi',
    name: 'IIT Delhi (Indian Institute of Technology)',
    category: 'btech',
    stream: 'btech',
    location: 'Hauz Khas, New Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹8.5 Lakhs (4-Yr Total)',
    feeNum: 8.5,
    avgPlacement: '₹25.8 LPA',
    avgPlacementNum: 25.8,
    highestPlacement: '₹2.0 Cr',
    cutoff: 'JEE Advanced Rank < 2000',
    ranking: 'NIRF #2 Engineering',
    exams: ['JEE Advanced'],
    tag: 'Govt • Top Tech Institute',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/iit-delhi',
    rating: '4.9',
    ownership: 'Institute of National Importance',
    approvals: 'MHRD Govt of India',
  },
  {
    id: 'iiit-delhi',
    name: 'IIIT Delhi (Indraprastha Institute of IT)',
    category: 'btech',
    stream: 'btech',
    location: 'Okhla, New Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹18.0 Lakhs (4-Yr Total)',
    feeNum: 18.0,
    avgPlacement: '₹23.7 LPA',
    avgPlacementNum: 23.7,
    highestPlacement: '₹51.3 LPA',
    cutoff: 'JEE Main 98+ %ile (JAC)',
    ranking: 'Premier CS & AI Hub',
    exams: ['JEE Main (JAC Delhi)'],
    tag: 'Govt Autonomous • CS/AI',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/iiit-delhi',
    rating: '4.8',
    ownership: 'Delhi Govt State University',
    approvals: 'UGC, NAAC A',
  },
  {
    id: 'dtu-delhi',
    name: 'DTU (Delhi Technological University)',
    category: 'btech',
    stream: 'btech',
    location: 'Rohini, New Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹9.2 Lakhs (4-Yr Total)',
    feeNum: 9.2,
    avgPlacement: '₹16.5 LPA',
    avgPlacementNum: 16.5,
    highestPlacement: '₹82.0 LPA',
    cutoff: 'JEE Main Rank (JAC Delhi)',
    ranking: 'NIRF Top 30 • DCE Legacy',
    exams: ['JEE Main (JAC Delhi)'],
    tag: 'Delhi Govt • Tech Legacy',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/delhi-technological-university-dtu',
    rating: '4.8',
    ownership: 'State Government University',
    approvals: 'UGC, AICTE',
  },
  {
    id: 'coep-pune',
    name: 'COEP Technological University Pune',
    category: 'btech',
    stream: 'btech',
    location: 'Shivajinagar, Pune, Maharashtra',
    state: 'Maharashtra',
    city: 'Pune',
    fees: '₹4.5 Lakhs (4-Yr Total)',
    feeNum: 4.5,
    avgPlacement: '₹12.8 LPA',
    avgPlacementNum: 12.8,
    highestPlacement: '₹50.5 LPA',
    cutoff: 'MHT CET 99+ %ile / JEE',
    ranking: '3rd Oldest Engg College in Asia',
    exams: ['MHT CET', 'JEE Main'],
    tag: 'Govt Autonomous • Pune Hub',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/coep-pune',
    rating: '4.8',
    ownership: 'State Govt Autonomous',
    approvals: 'AICTE, NBA, NAAC A+',
    isHighRoi: true,
  },
  {
    id: 'rvce-bangalore',
    name: 'RV College of Engineering (RVCE)',
    category: 'btech',
    stream: 'btech',
    location: 'Mysore Road, Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees: '₹10.5 Lakhs (4-Yr Total)',
    feeNum: 10.5,
    avgPlacement: '₹15.5 LPA',
    avgPlacementNum: 15.5,
    highestPlacement: '₹62.0 LPA',
    cutoff: 'KCET Top 500 / COMEDK 98%ile',
    ranking: 'NIRF Top Engineering Karnataka',
    exams: ['KCET', 'COMEDK', 'Direct Management Quota'],
    tag: 'Bangalore #1 Private Engg',
    tagColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    slug: 'colleges/rvce-bangalore',
    rating: '4.8',
    ownership: 'Private Autonomous',
    approvals: 'AICTE, VTU, NBA',
    hasDirectAdmission: true,
  },

  // ── Top Undergraduate Foundations (BBA / BCA / B.Com) ──
  {
    id: 'sscbs-delhi',
    name: 'SSCBS (Shaheed Sukhdev College of Business Studies)',
    category: 'ug',
    stream: 'ug',
    location: 'Rohini, New Delhi',
    state: 'Delhi NCR',
    city: 'Delhi',
    fees: '₹65,000 (3-Yr Total)',
    feeNum: 0.65,
    avgPlacement: '₹10.5 LPA',
    avgPlacementNum: 10.5,
    highestPlacement: '₹44.0 LPA',
    cutoff: 'CUET-UG Top Percentile',
    ranking: 'India #1 BBA / BMS College',
    exams: ['CUET-UG'],
    tag: 'DU Govt • India #1 BBA',
    tagColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    slug: 'colleges/sscbs-delhi-university',
    rating: '4.9',
    ownership: 'Government (Delhi University)',
    approvals: 'UGC, Delhi University',
    isHighRoi: true,
  },
  {
    id: 'christ-ug',
    name: 'Christ University Bangalore (BBA / BCA / BCom)',
    category: 'ug',
    stream: 'ug',
    location: 'Hosur Road, Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees: '₹5.5 Lakhs (3-Yr Total)',
    feeNum: 5.5,
    avgPlacement: '₹6.8 LPA',
    avgPlacementNum: 6.8,
    highestPlacement: '₹21.0 LPA',
    cutoff: 'CUET / Christ Entrance Test',
    ranking: 'NIRF Top 60 • NAAC A+',
    exams: ['Christ Entrance Test', 'Merit'],
    tag: 'Top Bangalore UG Campus',
    tagColor: 'bg-purple-100 text-purple-900 border-purple-300',
    slug: 'colleges/christ-university-bangalore',
    rating: '4.7',
    ownership: 'Deemed University',
    approvals: 'UGC, NAAC A+',
    hasDirectAdmission: true,
  }
];
