import {
  BarChart2,
  PieChart,
  Database,
  Activity,
  Cloud,
  ShieldCheck,
  Server,
  Table,
  LucideIcon
} from "lucide-react";

export type Question = {
  q: string;
  options: string[];
  answer: number;
};

export type SkillModule = {
  title: string;
  content: string;
};

export type Skill = {
  id: string;
  title: string;
  icon: LucideIcon;
  color: string;
  description: string;
  modules: SkillModule[];
  questions: Question[];
};

export const SKILLS: Skill[] = [
  {
    id: "powerbi",
    title: "Power BI",
    icon: BarChart2,
    color: "bg-yellow-500",
    description: "Master data visualization, DAX, and business intelligence reporting for strategic decision-making.",
    modules: [
      {
        title: "Introduction to Business Intelligence & Power BI",
        content: "Understand the fundamentals of BI and the Power BI ecosystem, including Power BI Desktop, Service, and Mobile. You'll learn how BI drives business value and why Power BI is an industry-leading tool."
      },
      {
        title: "Data Extraction & Transformation (Power Query)",
        content: "Learn to connect to diverse data sources (Excel, SQL, APIs) and clean, shape, and transform data using Power Query Editor. This step ensures data is structured properly for downstream analysis."
      },
      {
        title: "Data Modeling & DAX Expressions",
        content: "Master the creation of robust data models using relationships (1-to-many, many-to-many). Dive deep into Data Analysis Expressions (DAX) to create calculated columns and advanced measures."
      },
      {
        title: "Visualizations & Interactive Dashboards",
        content: "Build compelling visual reports using charts, tables, maps, and custom visuals. Learn to implement interactive features like drill-throughs, tooltips, and slicers to enhance user experience."
      },
      {
        title: "Advanced Analytics & Deployment",
        content: "Explore AI-driven visuals (Q&A, Decomposition Tree) and learn how to publish reports to Power BI Service, schedule automatic dataset refreshes, and set up role-level security (RLS)."
      }
    ],
    questions: [
      { q: "What is the primary function of Power Query?", options: ["Data Modeling", "Data Extraction and Transformation", "Creating Dashboards", "Sharing Reports"], answer: 1 },
      { q: "Which of the following is NOT a component of the Power BI ecosystem?", options: ["Power BI Desktop", "Power BI Service", "Power BI Analytics Server", "Power BI Report Builder"], answer: 2 },
      { q: "What does DAX stand for?", options: ["Data Analytics XML", "Data Analysis Expressions", "Dynamic Analysis Extractor", "Data Assessment X"], answer: 1 },
      { q: "Which feature allows you to restrict data view access based on user roles?", options: ["Row-Level Security (RLS)", "Data Masking", "Column-Level Control", "User Filter Groups"], answer: 0 },
      { q: "What type of join in Power BI mapping returns only matching rows from both tables?", options: ["Left Outer", "Inner", "Full Outer", "Right Outer"], answer: 1 },
      { q: "Which tool within Power BI is specifically used to write custom M code?", options: ["DAX Editor", "Visual Studio", "Advanced Editor in Power Query", "Model View"], answer: 2 },
      { q: "When would you prefer a Calculated Column over a Measure in DAX?", options: ["When aggregating values dynamically on a visual", "When slicing or filtering row-by-row data", "To improve query performance during report rendering", "Never, measures are always better"], answer: 1 },
      { q: "What distinguishes an Implicit Measure from an Explicit Measure?", options: ["Implicit is written in DAX; Explicit is drag-and-drop", "Implicit is automatically generated by Power BI; Explicit is custom-written in DAX", "Implicit can only be used on Service; Explicit only on Desktop", "There is no difference"], answer: 1 },
      { q: "Which Power BI visual is best suited for showing the continuous relationship between two variables?", options: ["Pie Chart", "Scatter Plot", "Card Visual", "Treemap"], answer: 1 },
      { q: "What does the CALCULATE function essentially do in DAX?", options: ["Calculates basic arithmetic", "Transforms data types", "Modifies the filter context for an expression", "Creates a new table"], answer: 2 },
      { q: "Which relationship cardinality is most common and recommended in a star schema?", options: ["One-to-One", "One-to-Many", "Many-to-Many", "Many-to-One"], answer: 1 },
      { q: "What is a major advantage of the DirectQuery mode compared to Import mode?", options: ["Supports all DAX functions seamlessly", "Data doesn't need to be refreshed manually/scheduled to show real-time changes", "Faster dashboard rendering times", "Easier data transformations"], answer: 1 },
      { q: "Which of the following DAX functions is considered an 'iterator' function?", options: ["SUM", "AVERAGE", "SUMX", "COUNT"], answer: 2 },
      { q: "How can you implement a 'drill-through' in Power BI?", options: ["By right-clicking a data point to navigate to a detailed report page focused on that specific entity", "By using the Q&A visual", "By writing advanced DAX filters", "It's a premium-only feature configured in Service"], answer: 0 },
      { q: "What visual is best for seeing the hierarchical breakdown of a particular metric?", options: ["Gauges", "Key Influencers", "Decomposition Tree", "Filled Map"], answer: 2 },
      { q: "What is the standard underlying language of Power Query?", options: ["Python", "SQL", "M Formula Language", "DAX"], answer: 2 },
      { q: "In Power BI Service, what is a Workspace?", options: ["A file extension", "A collaborative area to manage and distribute content", "A local desktop folder", "A premium licensing tier"], answer: 1 },
      { q: "What is the primary benefit of a Star Schema over a flat table?", options: ["It uses less storage and optimizes DAX evaluation performance", "It allows for unlimited columns", "It eliminates the need for DAX", "It is easier to import from Excel"], answer: 0 },
      { q: "Which DAX function would you use to ignore all filters on a specific table?", options: ["FILTER", "REMOVEFILTERS / ALL", "IGNORE", "CALCULATE"], answer: 1 },
      { q: "If your underlying SQL database adds a new column, how do you see it in Power BI Desktop?", options: ["Restart Power BI", "Click 'Refresh' on the ribbon", "Go to Power Query and refresh the preview/apply steps", "It appears automatically in real-time"], answer: 2 }
    ]
  },
  {
    id: "tableau",
    title: "Tableau",
    icon: PieChart,
    color: "bg-blue-600",
    description: "Learn visual analytics, data blending, and creating intuitive dashboards.",
    modules: [
      {
        title: "Intro to Visual Analytics & Tableau Architecture",
        content: "Explore the Tableau workspace, difference between Desktop, Prep, and Server, and the fundamental concepts of dimensions vs. measures."
      },
      {
        title: "Data Connections & Preparation",
        content: "Learn how to connect to live databases vs. extracts, blend multiple data sources, and join cross-database tables efficiently."
      },
      {
        title: "Building Fundamental Visualizations",
        content: "Create foundational charts like bar charts, line graphs, dual-axis charts, and geodatabase maps. Understand the Show Me panel."
      },
      {
        title: "Advanced Calculations & Parameters",
        content: "Implement Level of Detail (LOD) expressions, Quick Table Calculations, and dynamic Parameters to allow user-driven interactivity."
      },
      {
        title: "Interactive Dashboards & Storytelling",
        content: "Assemble interactive dashboards using action filters (hover, select, menu) and construct narrative-driven Story Points for business presentations."
      }
    ],
    questions: [
      { q: "What is the distinct difference between a Measure and a Dimension in Tableau?", options: ["Dimensions contain qualitative values; Measures contain numeric, quantitative values", "Dimensions are always blue; Measures are always green", "Dimensions are for charts; Measures are for text tables", "There is no difference"], answer: 0 },
      { q: "Which data connection acts as a snapshot of your dataset saved locally?", options: ["Live Connection", "TDS File", "Tableau Data Extract (.hyper/.tde)", "Web Data Connector"], answer: 2 },
      { q: "What file type saves a packaged Tableau workbook, including local data extracts?", options: [".twb", ".twbx", ".tde", ".tds"], answer: 1 },
      { q: "In Tableau, what indicates a discrete variable on the shelves?", options: ["A green pill", "A blue pill", "A red outline", "An italicized font"], answer: 1 },
      { q: "Which Level of Detail (LOD) expression computes an aggregation independent of the current view's level of detail?", options: ["FIXED", "INCLUDE", "EXCLUDE", "ABSOLUTE"], answer: 0 },
      { q: "What feature in Tableau allows you to replace a constant value in a calculation with a dynamic value controlled by the user?", options: ["Filters", "Sets", "Parameters", "Groups"], answer: 2 },
      { q: "To show sales trends over time alongside profit margin percentage on the same chart, you should use:", options: ["A Gantt Chart", "A Scatter Plot", "A Dual-Axis Chart", "A Pie chart"], answer: 2 },
      { q: "What is 'Data Blending' in Tableau?", options: ["Merging cells in a text table", "Combining data from multiple, disparate data sources on a single sheet using a common linking field", "Cleaning null values automatically", "Converting string dates to date formats"], answer: 1 },
      { q: "Which tool automatically generates summary visualizations based on selected fields?", options: ["Analytics Pane", "Show Me", "Data Source Tab", "Pages Shelf"], answer: 1 },
      { q: "What is a key characteristic of 'Dashboard Actions'?", options: ["They schedule data refreshes", "They allow elements of a dashboard to act as filters or links for other elements", "They translate workbooks to different languages", "They export views to PDF"], answer: 1 },
      { q: "How do you distinguish a calculated field from a standard field in the Data Pane?", options: ["It has a golden star", "It has an '=' preceding the data type icon", "It is always capitalized", "It sits in a separate folder automatically"], answer: 1 },
      { q: "Which filter type executes earliest in Tableau's Order of Operations?", options: ["Extract Filter", "Context Filter", "Dimension Filter", "Measure Filter"], answer: 0 },
      { q: "What is the main use case for Context Filters?", options: ["To force a filter to occur before FIXED LOD expressions and improve performance", "To filter dates only", "To filter data dynamically across multiple dashboards", "To change the visual's background context"], answer: 0 },
      { q: "What happens when you drop a dimension onto the 'Color' mark?", options: ["It changes the background color", "It assigns a distinct color to each categorical member of the dimension", "It creates a continuous color gradient", "It returns an error"], answer: 1 },
      { q: "To group customers ranking in the top 10% versus the rest, which feature is best utilized?", options: ["Parameters", "Format pane", "Sets", "Story Points"], answer: 2 },
      { q: "Tableau 'Story Points' are primarily designed to:", options: ["Write DAX code", "Build relational database diagrams", "Present a narrative through a sequence of dashboards or sheets", "Import flat files into SQL databases"], answer: 2 },
      { q: "Which chart is effectively used to display hierarchical data as a set of nested rectangles?", options: ["Treemap", "Heat Map", "Highlight Table", "Bullet Graph"], answer: 0 },
      { q: "What does 'Show Missing Values' do when applied to a date dimension?", options: ["Automatically inserts average values", "Fills in visual gaps on the axis for dates without underlying records", "Deletes rows with nulls", "Emails an error log"], answer: 1 },
      { q: "What differentiates a Group from a Set in Tableau?", options: ["Groups combine specific dimension members into higher-level categories; Sets establish custom subsets based on conditions", "There is no difference", "Groups are dynamic, Sets are static", "Groups can only be used on metrics"], answer: 0 },
      { q: "Which function converts a string, like '01-Jan', into a valid Date format?", options: ["STR()", "DATETIME()", "DATEPARSE() or DATE()", "INT()"], answer: 2 }
    ]
  },
  {
    id: "sql",
    title: "SQL",
    icon: Database,
    color: "bg-indigo-500",
    description: "Query databases, write complex joins, and manage massive datasets.",
    modules: [
      {
        title: "Relational Database Basics & RDBMS",
        content: "Understand primary keys, foreign keys, and entity-relationship models. Learn what defines a Relational Database Management System (RDBMS)."
      },
      {
        title: "Basic CRUD & Filtering",
        content: "Master CREATE, READ, UPDATE, and DELETE syntax. Use standard WHERE clauses, IN operators, LIKE wildcards, and logical operators for exact filtering."
      },
      {
        title: "Aggregations & Grouping",
        content: "Leverage GROUP BY, HAVING, and aggregate functions (SUM, AVG, COUNT, MIN, MAX) to derive macro-insights from raw data tables."
      },
      {
        title: "Joins and Subqueries",
        content: "Navigate multi-table databases using INNER, LEFT, RIGHT, and FULL joins. Understand Correlated Subqueries and Common Table Expressions (CTEs)."
      },
      {
        title: "Window Functions & Optimization",
        content: "Perform advanced analytics using OVER() clauses, ROW_NUMBER(), RANK(), and running totals. Discover basic index concepts and query optimization profiling."
      }
    ],
    questions: [
      { q: "What does SQL stand for?", options: ["Structured Query Language", "Standard Query Logic", "Systematic Query Language", "Structured Quick Logic"], answer: 0 },
      { q: "Which command is used to retrieve data from a database?", options: ["EXTRACT", "SELECT", "PULL", "GET"], answer: 1 },
      { q: "What does the WHERE clause do?", options: ["Sorts the results", "Filters records based on a specified condition", "Groups rows that have the same values", "Joins two tables"], answer: 1 },
      { q: "Which type of JOIN returns all records from both tables, with NULLs matching where there is no relationship?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], answer: 3 },
      { q: "What is a Primary Key?", options: ["The first column in a table", "A unique identifier for each record in a table", "A key used to encrypt the database", "A column that only accepts numeric values"], answer: 1 },
      { q: "Which SQL operator is used to search for a specified pattern in a column (e.g., matching a subset of text)?", options: ["MATCH", "LIKE", "SEARCH", "PATTERN"], answer: 1 },
      { q: "Which defining clause must be used with aggregate functions (like SUM) if you also select non-aggregated columns?", options: ["ORDER BY", "WHERE", "GROUP BY", "HAVING"], answer: 2 },
      { q: "What is the difference between WHERE and HAVING?", options: ["WHERE filters before data is grouped; HAVING filters after data is grouped", "WHERE is for numbers; HAVING is for text", "HAVING filters before grouping; WHERE filters after", "There is no functional difference"], answer: 0 },
      { q: "Which keyword is used to sort the result-set?", options: ["SORT BY", "ORDER BY", "ALIGN", "SEQUENCE BY"], answer: 1 },
      { q: "In SQL, what is a View?", options: ["A temporary table deleted after the session", "A graphical GUI interface for the database", "A virtual table based on the result-set of an SQL statement", "A backup of the database"], answer: 2 },
      { q: "What command is used to remove a table entirely (including its underlying structure and data)?", options: ["DELETE TABLE", "TRUNCATE TABLE", "DROP TABLE", "REMOVE TABLE"], answer: 2 },
      { q: "Which window function assigns a unique sequential integer to rows within a partition of a result set?", options: ["RANK()", "DENSE_RANK()", "ROW_NUMBER()", "NTILE()"], answer: 2 },
      { q: "What is an Index in SQL databases used for?", options: ["To store multimedia files", "To encrypt text fields", "To speed up data retrieval operations", "To export data to CSV"], answer: 2 },
      { q: "Which statement properly creates a Common Table Expression (CTE)?", options: ["WITH CTE_Name AS (SELECT...)", "CREATE CTE CTE_Name AS...", "DECLARE CTE_Name = SELECT...", "TEMP_TABLE CTE_Name AS..."], answer: 0 },
      { q: "What does the COUNT(1) or COUNT(*) function do?", options: ["Adds up the values of column 1", "Counts the total number of rows in the table or group", "Returns 1 if the table has rows", "Counts unique non-null values only"], answer: 1 },
      { q: "Which normalized form primarily deals with eliminating transitive dependencies?", options: ["First Normal Form (1NF)", "Second Normal Form (2NF)", "Third Normal Form (3NF)", "Boyce-Codd Normal Form"], answer: 2 },
      { q: "What is the purpose of the TRUNCATE command?", options: ["To delete specific rows via WHERE", "To quickly remove all records from a table while keeping the structure", "To drop the table entirely", "To remove blank spaces from strings"], answer: 1 },
      { q: "If you want to ensure no duplicate rows are returned in your selection, what keyword do you add?", options: ["UNIQUE", "DISTINCT", "NO_DUPLICATES", "SINGLE"], answer: 1 },
      { q: "What does a Foreign Key do?", options: ["Encrypts remote connections", "Specifies a language encoding", "Links records to the Primary Key of another table to enforce referential integrity", "Brings external CSV data into SQL"], answer: 2 },
      { q: "Which function calculates the running total using window capabilities?", options: ["SUM() OVER()", "CALCULATE()", "TOTAL_SUM()", "RUNNING_TOTAL()"], answer: 0 }
    ]
  },
  {
    id: "sixsigma",
    title: "Six Sigma",
    icon: Activity,
    color: "bg-purple-600",
    description: "Process improvement methodologies utilizing statistics to drastically reduce defects.",
    modules: [
      {
        title: "Introduction to Lean & Six Sigma",
        content: "Examine the origins of Lean (eliminating waste) and Six Sigma (reducing variation). Understand the meaning of a 3.4 DPMO standard."
      },
      {
        title: "The DMAIC Framework: Define & Measure",
        content: "Learn how to scope projects with Project Charters. Understand measurement system analysis (MSA) and baseline defect rates."
      },
      {
        title: "Analyze Phase & Root Cause",
        content: "Identify actionable root causes utilizing Fishbone (Ishikawa) diagrams, 5-Whys, and statistical hypothesis testing (ANOVA, T-Tests)."
      },
      {
        title: "Improve Phase",
        content: "Develop pilot solutions using Design of Experiments (DOE). Implement Kaizen events and Poka-Yoke (mistake-proofing) strategies."
      },
      {
        title: "Control Phase & Institutionalization",
        content: "Lock in gains using Statistical Process Control (SPC) charts, standard operating procedures (SOPs), and training hand-offs."
      }
    ],
    questions: [
      { q: "What is the central focus of Six Sigma?", options: ["Eliminating waste", "Reducing process variation and defects", "Increasing marketing reach", "Agile software development"], answer: 1 },
      { q: "Statistically, Six Sigma aims to achieve a defect rate of no more than:", options: ["1.5 DPMO", "3.4 DPMO", "Zero defects", "100 DPMO"], answer: 1 },
      { q: "What does the acronym DMAIC stand for?", options: ["Define, Measure, Analyze, Improve, Control", "Data, Metrics, Analytics, Insights, Cost", "Design, Measure, Assess, Implement, Check", "Define, Map, Align, Improve, Control"], answer: 0 },
      { q: "Which tool is used in the Define phase to officially authorize a project?", options: ["Control Chart", "Project Charter", "DOE", "Fishbone Diagram"], answer: 1 },
      { q: "In Lean terminology, what does 'Muda' refer to?", options: ["Improvement", "Mistake-proofing", "Waste", "Value-add"], answer: 2 },
      { q: "The '5 Whys' technique is primarily used during which phase of DMAIC?", options: ["Define", "Measure", "Analyze", "Control"], answer: 2 },
      { q: "What represents the 'Voice of the Customer' (VOC)?", options: ["Internal audit findings", "Customer requirements, expectations, and feedback", "Shareholder dividend targets", "Employee satisfaction surveys"], answer: 1 },
      { q: "What is an Ishikawa diagram more commonly known as?", options: ["Pareto Chart", "Fishbone Diagram / Cause & Effect Diagram", "Control Chart", "Scatter Plot"], answer: 1 },
      { q: "The Pareto Principle states that roughly:", options: ["80% of consequences come from 20% of the causes", "100% perfection is impossible", "50% of defects are untraceable", "99.9% quality is standard"], answer: 0 },
      { q: "Which statistical concept measures the dispersion of data around the mean?", options: ["Median", "Mode", "Standard Deviation", "P-Value"], answer: 2 },
      { q: "What is 'Poka-Yoke'?", options: ["A Japanese martial art", "Mistake-proofing a process to prevent human error", "A type of control chart", "A statistical test for variance"], answer: 1 },
      { q: "In a Control Chart, what do the UCL and LCL represent?", options: ["Upper and Lower Control Limits", "User and Local Chart Levels", "Ultimate and Least Customer Limits", "Uniform and Linear Calculations"], answer: 0 },
      { q: "Which distribution assumes a bell-shaped curve that is symmetric around its mean?", options: ["Poisson Distribution", "Binomial Distribution", "Normal Distribution", "Exponential Distribution"], answer: 2 },
      { q: "Measurement System Analysis (MSA) is conducted to ensure:", options: ["The gauges and appraisers are consistent and reliable (Gage R&R)", "The project has enough funding", "The customer is satisfied", "The solution is mistake-proof"], answer: 0 },
      { q: "Who originated the Six Sigma methodology in the 1980s?", options: ["Toyota", "Motorola", "General Electric", "Ford"], answer: 1 },
      { q: "A 'Black Belt' in Six Sigma refers to:", options: ["A purely theoretical expert", "A full-time improvement project leader and statistical expert", "An executive sponsor", "An introductory level certification"], answer: 1 },
      { q: "What is CTQ?", options: ["Cost To Quality", "Critical To Quality", "Control The Quality", "Customer Transaction Query"], answer: 1 },
      { q: "What does 'Kaizen' generally mean?", options: ["Continuous Incremental Improvement", "Drastic Process Redesign", "Zero Defects", "Inventory Reduction"], answer: 0 },
      { q: "Design of Experiments (DOE) is heavily utilized in which phase?", options: ["Define", "Measure", "Analyze", "Improve"], answer: 3 },
      { q: "Which type of chart is used to evaluate process stability over time?", options: ["Control Chart", "Pie chart", "Histogram", "Gantt Chart"], answer: 0 }
    ]
  },
  {
    id: "cloudcomputing",
    title: "Cloud Computing",
    icon: Cloud,
    color: "bg-sky-500",
    description: "Understand IaaS, PaaS, SaaS models, cloud security, and distributed architecture.",
    modules: [
      {
        title: "Fundamentals & Delivery Models",
        content: "Learn essential cloud characteristics (on-demand, elasticity). Dive into differences between IaaS (Infrastructure), PaaS (Platform), and SaaS (Software)."
      },
      {
        title: "Deployment Architectures",
        content: "Evaluate Public, Private, Hybrid, and Multi-Cloud environments. Understand when and why enterprises choose hybrid structures."
      },
      {
        title: "Virtualization & Containers",
        content: "Discover how Hypervisors decouple OS from hardware. Trace the evolution from VMs to lightweight Docker Containers and Kubernetes Orchestration."
      },
      {
        title: "Cloud Storage & Databases",
        content: "Differentiate between Object Storage, Block Storage, and File Storage. Compare traditional RDBMS vs. highly scalable NoSQL cloud databases."
      },
      {
        title: "Cloud Security & Economics",
        content: "Understand the Shared Responsibility Model. Learn OpEx vs CapEx shifts and identity management (IAM) strategies."
      }
    ],
    questions: [
      { q: "Which key characteristic of cloud allows users to consume compute resources dynamically without human intervention?", options: ["Broad Network Access", "On-demand Self-Service", "Resource Pooling", "Measured Service"], answer: 1 },
      { q: "Microsoft Azure and Amazon Web Services primarily represent which type of deployment model?", options: ["Private Cloud", "Public Cloud", "Hybrid Cloud", "Community Cloud"], answer: 1 },
      { q: "Salesforce CRM or Google Workspace are classic examples of:", options: ["IaaS", "PaaS", "SaaS", "FaaS"], answer: 2 },
      { q: "What does 'Elasticity' mean in Cloud Computing?", options: ["The network speed adjusts based on distance", "Resources can automatically rapidly scale out/up or scale in/down based on demand", "Data is compressed continuously", "Pricing fluctuates by the hour"], answer: 1 },
      { q: "Which model provides you with operating systems, databases, and development tools without managing underlying hardware?", options: ["SaaS", "IaaS", "PaaS", "NaaS"], answer: 2 },
      { q: "What is a 'Hypervisor'?", options: ["High-speed fiber optic cables", "Software that creates and runs virtual machines by virtualizing hardware", "A security firewall", "A cloud billing metric"], answer: 1 },
      { q: "Which storage type is best for storing vast amounts of unstructured media (like video files) over the web?", options: ["Block Storage", "File/NFS Storage", "Object Storage (e.g., S3)", "Local Disk Storage"], answer: 2 },
      { q: "A mix of on-premises infrastructure and public cloud resources is called:", options: ["Multi-cloud", "Hybrid Cloud", "Distributed Cloud", "Private Cloud"], answer: 1 },
      { q: "What is the 'Shared Responsibility Model'?", options: ["Costs are shared among multiple tenants", "The cloud provider and the customer share security and compliance obligations", "Customers share server CPU cycles", "All responsibilities lie with the vendor"], answer: 1 },
      { q: "What major financial shift occurs when adopting Cloud Computing?", options: ["CapEx (Capital Expenditure) shifts to OpEx (Operational Expenditure)", "OpEx shifts to CapEx", "Taxes are entirely eliminated", "Hardware depreciation accelerates"], answer: 0 },
      { q: "What is 'Serverless Computing'?", options: ["Applications running without any servers existing", "A model where the cloud provider dynamically manages the allocation and provisioning of servers", "Local host processing only", "Database caching mechanisms"], answer: 1 },
      { q: "What isolates Docker containers on a single host machine?", options: ["Separate hypervisors", "The host machine's OS kernel features (e.g., namespaces, cgroups)", "Physical hardware segmentation", "They are never isolated"], answer: 1 },
      { q: "What role does Kubernetes play in cloud ecosystems?", options: ["It is an operating system", "It orchestrates and manages containerized applications at scale", "It is a serverless function runner", "It is an object storage bucket"], answer: 1 },
      { q: "Which type of scaling means adding more powerful hardware (CPU/RAM) to an existing server?", options: ["Scaling Out (Horizontal)", "Scaling Up (Vertical)", "Auto-Scaling", "Diagonal Scaling"], answer: 1 },
      { q: "A 'CDN' in networking and cloud stands for:", options: ["Continuous Data Node", "Content Delivery Network", "Cloud Desktop Node", "Compute Defense Network"], answer: 1 },
      { q: "In the context of high availability, what is a 'Region'?", options: ["A geographical area containing multiple isolated data centers", "A single rack of servers", "A virtual private network", "A billing category"], answer: 0 },
      { q: "Which feature protects against single data center total failure within a specific region?", options: ["Availability Zones (AZs)", "CDN caching", "Vertical Scaling", "VPC Peering"], answer: 0 },
      { q: "What is the main driver for 'Multi-Cloud' adoption?", options: ["Avoiding vendor lock-in and leveraging best-of-breed services from different providers", "It is required by law", "It reduces network latency to zero", "It consolidates all billing to one invoice"], answer: 0 },
      { q: "IaaS stands for:", options: ["Information as a Service", "Infrastructure as a Service", "Internet as a Server", "Intelligence as a Service"], answer: 1 },
      { q: "High fault tolerance implies that an architecture will:", options: ["Crash immediately but reboot fast", "Continue operating properly in the event of the failure of some of its components", "Reject malicious traffic automatically", "Require manual failover protocols"], answer: 1 }
    ]
  },
  {
    id: "cybersecurity",
    title: "Cyber Security",
    icon: ShieldCheck,
    color: "bg-red-500",
    description: "Protect systems, networks, and programs from digital attacks and unauthorized access.",
    modules: [
      {
        title: "The CIA Triad & Fundamentals",
        content: "Master the core pillars of security: Confidentiality, Integrity, and Availability. Understand the spectrum of threat actors."
      },
      {
        title: "Identity & Access Management (IAM)",
        content: "Explore Authentication vs. Authorization. Implement Multi-Factor Authentication (MFA), Principle of Least Privilege, and SSO."
      },
      {
        title: "Malware & Threat Vectors",
        content: "Identify Ransomware, Trojans, Rootkits, and Social Engineering attacks like Phishing and Spear-Phishing."
      },
      {
        title: "Network Security & Cryptography",
        content: "Understand basic Firewalls, IDS/IPS, VPNs. Discover Symmetric vs. Asymmetric encryption and modern hashing (SHA-256)."
      },
      {
        title: "Risk Management & Incident Response",
        content: "Learn how teams calculate risk, develop Disaster Recovery (DR) plans, and execute structured Incident Response protocols."
      }
    ],
    questions: [
      { q: "What are the three pillars of the CIA Triad?", options: ["Confidentiality, Integrity, Availability", "Control, Identity, Authorization", "Cyber, Intelligence, Analytics", "Confidentiality, Inspection, Access"], answer: 0 },
      { q: "What describes mitigating the risk that an unauthorized party modifies data in transit?", options: ["Confidentiality", "Integrity", "Availability", "Authentication"], answer: 1 },
      { q: "A targeted email attack aimed at a specific high-value individual (like a CEO) is called:", options: ["Spam", "Phishing", "Spear Phishing / Whaling", "Spoofing"], answer: 2 },
      { q: "What is ransomware?", options: ["Software that creates secret backdoors", "Malware that encrypts a victim's files and demands payment for the decryption key", "A tool used to scan for vulnerabilities", "An antivirus agent"], answer: 1 },
      { q: "Which principle dictates that users should only receive the minimum permissions necessary to perform their duties?", options: ["Principle of Minimum Access", "Zero Trust Principle", "Principle of Least Privilege", "Separation of Duties"], answer: 2 },
      { q: "What is the difference between Authentication and Authorization?", options: ["Authentication verifies WHO you are; Authorization verifies WHAT you are allowed to do", "They are exactly the same concept", "Authorization requires passwords, Authentication requires physical tokens", "Authentication is for software, Authorization is for physical doors"], answer: 0 },
      { q: "Multi-Factor Authentication (MFA) requires:", options: ["At least two forms of verification from different categories (something you know, have, or are)", "Two different passwords", "A complex password with numbers and symbols", "Checking your email twice"], answer: 0 },
      { q: "In Cryptography, what is Asymmetric Encryption?", options: ["Using the same key to encrypt and decrypt", "Using a mathematically linked public-key and private-key pair", "Encrypting data in chunks (blocks)", "Hashing passwords out of existence"], answer: 1 },
      { q: "A DDoS attack primarily threatens which component of the CIA Triad?", options: ["Confidentiality", "Integrity", "Availability", "Authorization"], answer: 2 },
      { q: "A Firewall's primary purpose is to:", options: ["Remove viruses from hard drives", "Filter incoming and outgoing network traffic based on predetermined security rules", "Encrypt email messages", "Provide wireless local access"], answer: 1 },
      { q: "What does a VPN (Virtual Private Network) essentially do?", options: ["Prevents phishing emails", "Creates an encrypted tunnel for data transmission over public networks", "Removes adware from browsers", "Physically isolates hardware data centers"], answer: 1 },
      { q: "Which form of malware disguises itself as legitimate software to trick users into executing it?", options: ["Worm", "Trojan Horse", "Keylogger", "Ransomware"], answer: 1 },
      { q: "What does 'Zero Trust' architecture mean?", options: ["Never trust anyone; always verify every request regardless of origin", "Never install antivirus", "Trust internal networks completely, but block all outside traffic", "Assume every employee is a malicious actor entirely"], answer: 0 },
      { q: "A 'White Hat' hacker is:", options: ["An attacker seeking financial gain", "A state-sponsored espionage agent", "An ethical hacker hired to find and fix vulnerabilities", "A hacker who strictly uses Linux"], answer: 2 },
      { q: "What is SQL Injection?", options: ["A physical attack on a database server", "A malicious code entry technique that manipulates backend database queries", "A database backup methodology", "A firewall bypassing mechanism"], answer: 1 },
      { q: "Hashing is a cryptographic process that is:", options: ["Reversible with the right key", "One-way and cannot be fully 'decrypted' back to the original text", "Used primarily for video compression", "Outdated and insecure"], answer: 1 },
      { q: "In incident response, what is the 'Containment' phase?", options: ["Identifying that a breach occurred", "Isolating affected systems to prevent the incident from spreading", "Restoring systems from backups", "Reviewing post-incident lessons learned"], answer: 1 },
      { q: "Social Engineering relies primarily on:", options: ["Cracking algorithms", "Exploiting human psychology and trust", "Brute force password attempts", "Buffer overflow attacks"], answer: 1 },
      { q: "What is an IDS (Intrusion Detection System)?", options: ["A system that actively blocks unauthorized access", "A monitoring system that detects suspicious activity and raises alerts but does not block it", "A cryptographic key generator", "A spam filter"], answer: 1 },
      { q: "Patch Management is critical because it:", options: ["Updates GUI themes", "Resolves known software vulnerabilities that attackers could exploit", "Speeds up network connections", "Reduces physical hardware temperature"], answer: 1 }
    ]
  },
  {
    id: "aws",
    title: "AWS",
    icon: Server,
    color: "bg-orange-500",
    description: "Deploy, manage, and scale cloud applications on Amazon Web Services ecosystem.",
    modules: [
      {
        title: "Global Infrastructure & Core Services",
        content: "Understand Regions, Availability Zones (AZs), and Edge Locations. Differentiate standard services like EC2, S3, and RDS."
      },
      {
        title: "Compute: EC2 instances & Serverless",
        content: "Learn how to provision Virtual Private Servers (EC2). Explore Auto-Scaling Groups and AWS Lambda for serverless, event-driven functions."
      },
      {
        title: "Storage & Content Delivery",
        content: "Dive deep into Amazon S3 storage classes, EBS (Elastic Block Store) for EC2, and CloudFront as a fast CDN."
      },
      {
        title: "Networking & Security (VPC & IAM)",
        content: "Construct locked-down Virtual Private Clouds (VPCs) with subnets, security groups, and routing. Master AWS IAM for identity management."
      },
      {
        title: "Databases & Monitoring",
        content: "Compare Relational (RDS/Aurora) vs. NoSQL (DynamoDB). Utilize CloudWatch for alarms, logging, and metrics monitoring."
      }
    ],
    questions: [
      { q: "Which AWS service is foundational for Identity and Access Management?", options: ["AWS Shield", "Amazon Cognito", "AWS IAM", "AWS Config"], answer: 2 },
      { q: "What is an Amazon EC2 instance?", options: ["An object storage bucket", "A virtual server in the cloud", "A managed relational database", "A DNS routing service"], answer: 1 },
      { q: "In Amazon S3, what represents the fundamental container for objects?", options: ["Folders", "Directories", "Buckets", "Vaults"], answer: 2 },
      { q: "Which S3 storage class is best suited for long-term data archiving with retrieval times of hours?", options: ["S3 Standard", "S3 Intelligent-Tiering", "S3 Glacier / Glacier Deep Archive", "S3 One Zone-IA"], answer: 2 },
      { q: "What is AWS Lambda?", options: ["A large scale data warehouse", "A Serverless compute service that runs code in response to events", "A graph database", "An orchestrator for Docker containers"], answer: 1 },
      { q: "A logically isolated virtual network that you define in AWS is called a:", options: ["VLAN", "Virtual Private Cloud (VPC)", "Direct Connect", "AWS Outpost"], answer: 1 },
      { q: "Which service distributes incoming application traffic across multiple EC2 instances?", options: ["Elastic Load Balancing (ELB)", "Amazon Route 53", "AWS Auto Scaling", "Amazon CloudFront"], answer: 0 },
      { q: "What acts as a virtual firewall for your EC2 instances specifically to control inbound and outbound traffic?", options: ["Network ACL", "Security Groups", "WAF", "AWS Shield"], answer: 1 },
      { q: "Which fully managed, fast NoSQL database service is provided by AWS?", options: ["Amazon RDS", "Amazon Redshift", "Amazon DynamoDB", "Amazon Aurora"], answer: 2 },
      { q: "Which AWS service provides DNS routing and domain registration?", options: ["Amazon API Gateway", "Amazon CloudFront", "Amazon Route 53", "AWS Direct Connect"], answer: 2 },
      { q: "AWS CloudTrail is primarily used for:", options: ["Monitoring hardware performance metrics", "Logging user activity and API calls for governance and auditing", "Distributing content globally", "Hosting web applications"], answer: 1 },
      { q: "What block storage service is typically attached to an EC2 instance as its hard drive?", options: ["Amazon EFS", "Amazon EBS", "Amazon S3", "AWS Storage Gateway"], answer: 1 },
      { q: "What is the primary benefit of deploying an application across multiple Availability Zones?", options: ["It reduces compute costs by 50%", "High availability and fault tolerance against data center failures", "It automatically translates the app language", "It connects physical on-premise servers"], answer: 1 },
      { q: "Amazon CloudFront is technically what kind of service?", options: ["A data querying tool", "A Global Content Delivery Network (CDN)", "A relational database", "A serverless framework"], answer: 1 },
      { q: "What does Amazon RDS stand for?", options: ["Rapid Delivery Service", "Relational Database Service", "Redshift Data System", "Remote Data Server"], answer: 1 },
      { q: "Which service offers data warehousing for complex analytical BI queries?", options: ["Amazon Redshift", "Amazon RDS", "Amazon DynamoDB", "AWS Glue"], answer: 0 },
      { q: "When following the AWS Well-Architected Framework, which pillar focuses on recovering from failures?", options: ["Security", "Cost Optimization", "Reliability", "Performance Efficiency"], answer: 2 },
      { q: "What service sends email or text message notifications triggered by AWS systems?", options: ["Amazon SES", "Amazon SNS (Simple Notification Service)", "Amazon SQS", "AWS Step Functions"], answer: 1 },
      { q: "An AWS Edge Location is primarily used by which service?", options: ["Amazon EC2", "Amazon CloudFront", "Amazon S3", "AWS Lambda"], answer: 1 },
      { q: "If you want to view alarms and detailed metrics (like CPU usage percentage) for AWS resources, you use:", options: ["AWS CloudWatch", "AWS CloudTrail", "AWS Config", "AWS Inspector"], answer: 0 }
    ]
  },
  {
    id: "excel",
    title: "Advanced Excel",
    icon: Table,
    color: "bg-emerald-600",
    description: "Master advanced formulas, dynamic Pivot Tables, Macros, and intense data modeling algorithms.",
    modules: [
      {
        title: "Advanced Formulas & Logic",
        content: "Go beyond SUM. Master VLOOKUP, XLOOKUP, INDEX-MATCH, nested IF statements, and complex array formulas."
      },
      {
        title: "Data Cleaning & Validation",
        content: "Use Text-to-Columns, Remove Duplicates, and implement strict Data Validation rules to ensure flawless spreadsheet integrity."
      },
      {
        title: "Pivot Tables & Slicers",
        content: "Quickly synthesize millions of rows into actionable summaries. Add interactive Slicers and Timelines for robust dashboarding."
      },
      {
        title: "What-If Analysis & Goal Seek",
        content: "Forecast outcomes using Scenario Manager, Data Tables, and Goal Seek algorithms for complex financial modeling."
      },
      {
        title: "Macros & Basic VBA",
        content: "Automate highly repetitive tasks by recording Macros. Understand the basics of Visual Basic for Applications (VBA) to manually edit scripts."
      }
    ],
    questions: [
      { q: "What is a major limitation of VLOOKUP that INDEX-MATCH overcomes?", options: ["VLOOKUP cannot return text strings", "VLOOKUP only searches left-to-right (the lookup value must be in the first column)", "VLOOKUP is slower for small datasets", "VLOOKUP cannot be combined with IFERROR"], answer: 1 },
      { q: "In modern Excel versions, what highly versatile function replaces VLOOKUP and HLOOKUP directly?", options: ["CHOOSE", "XLOOKUP", "FILTER", "MATCH"], answer: 1 },
      { q: "What does putting a '$' sign before a row number in a cell reference (e.g., A$1) do?", options: ["Formats the cell as currency", "Creates an absolute row reference so it won't shift when dragged down", "Initiates a macro", "Multiplies the value by 100"], answer: 1 },
      { q: "What tool is best for restricting user input in a cell to a specific dropdown list?", options: ["Conditional Formatting", "Protect Sheet", "Data Validation", "Text to Columns"], answer: 2 },
      { q: "Pivot Tables are primarily used to:", options: ["Encrypt sensitive workbook data", "Summarize and analyze large amounts of tabular data dynamically", "Solve linear optimization problems automatically", "Import data from external SQL databases"], answer: 1 },
      { q: "Which tool visually filters data in a Pivot Table with an interactive clicking interface?", options: ["Sort", "Slicer", "Calculated Field", "Autofill"], answer: 1 },
      { q: "The 'Goal Seek' feature is found under which overarching Excel category?", options: ["Conditional Formatting", "What-If Analysis", "Text to Columns", "Review Toolbar"], answer: 1 },
      { q: "How do you automatically highlight rows where sales exceed $10,000?", options: ["Write a VBA script", "Apply a custom Pivot Table", "Create a Conditional Formatting rule", "Use Data Validation"], answer: 2 },
      { q: "What happens if a VLOOKUP cannot find an exact match when the 'range_lookup' parameter is FALSE/0?", options: ["It returns the closest approximation", "It deletes the row", "It returns an #N/A error", "It prompts the user to enter a value"], answer: 2 },
      { q: "What is a 'Calculated Field' in the context of a Pivot Table?", options: ["A field that calculates the total row count", "A custom geometric measure", "A custom field manually created by applying mathematical operations to existing fields in the Pivot Table", "A cell containing =SUM() outside the table"], answer: 2 },
      { q: "If you need to split 'John Doe' in one cell into 'John' and 'Doe' across two cells, you should use:", options: ["Concatenate", "Text to Columns", "Filter", "Data Validation"], answer: 1 },
      { q: "Which shortcut locks references, cycling through relative, absolute, and mixed ($) references?", options: ["F2", "F4", "F9", "Alt+Enter"], answer: 1 },
      { q: "What is a Macro in Excel?", options: ["A very large chart", "A recorded sequence of actions or VBA code that automates repetitive tasks", "A financial equation", "A database connection protocol"], answer: 1 },
      { q: "VBA stands for:", options: ["Visual Basics for Applications", "Variable Binary Array", "Visual Bracket Algorithms", "Virtual Build Architecture"], answer: 0 },
      { q: "Which function elegantly combines taking action if a formula evaluates to an error?", options: ["IF()", "ISERROR()", "IFERROR()", "MATCH()"], answer: 2 },
      { q: "What is the primary power of the Power Pivot add-in?", options: ["It adds new chart colors", "It handles massive data models exceeding the 1M row limit and utilizes DAX", "It exports spreadsheets to PowerPoint faster", "It records macros automatically"], answer: 1 },
      { q: "The CONCATENATE (or CONCAT) function is used to:", options: ["Divide numbers", "Ensure formulas do not error", "Combine or join text from multiple separate cells together", "Filter tables rapidly"], answer: 2 },
      { q: "What is an Excel Array Formula?", options: ["A formula that performs multiple calculations on one or more items in an array, returning either a single result or multiple results", "A formula designed strictly for strings", "A legacy formula no longer supported", "A macro recorder setting"], answer: 0 },
      { q: "When using What-If Analysis, which tool allows you to swap up to 32 different preset variables to view outcome changes?", options: ["Goal Seek", "Scenario Manager", "Solver", "Data Table"], answer: 1 },
      { q: "How do you enforce that a worksheet's structure cannot be changed (e.g., no adding/deleting sheets)?", options: ["Protect Workbook configuration", "Protect Sheet configuration", "Save as read-only PDF", "Lock specific cells"], answer: 0 }
    ]
  }
];
